# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import parser_pb2 as parser__pb2


class ParserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Parse = channel.unary_unary(
        '/Parser/Parse',
        request_serializer=parser__pb2.Expression.SerializeToString,
        response_deserializer=parser__pb2.Result.FromString,
        )


class ParserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Parse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ParserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Parse': grpc.unary_unary_rpc_method_handler(
          servicer.Parse,
          request_deserializer=parser__pb2.Expression.FromString,
          response_serializer=parser__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Parser', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
