# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import adder_pb2 as adder__pb2


class AdderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/Adder/Add',
        request_serializer=adder__pb2.Number.SerializeToString,
        response_deserializer=adder__pb2.AddedResult.FromString,
        )


class AdderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=adder__pb2.Number.FromString,
          response_serializer=adder__pb2.AddedResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Adder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
