# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='adder.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61\x64\x64\x65r.proto\"(\n\x06Number\x12\x0e\n\x06value1\x18\x01 \x01(\x05\x12\x0e\n\x06value2\x18\x02 \x01(\x05\"\x1c\n\x0b\x41\x64\x64\x65\x64Result\x12\r\n\x05value\x18\x01 \x01(\x05\x32\'\n\x05\x41\x64\x64\x65r\x12\x1e\n\x03\x41\x64\x64\x12\x07.Number\x1a\x0c.AddedResult\"\x00\x62\x06proto3')
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value1', full_name='Number.value1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value2', full_name='Number.value2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=55,
)


_ADDEDRESULT = _descriptor.Descriptor(
  name='AddedResult',
  full_name='AddedResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='AddedResult.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['AddedResult'] = _ADDEDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'adder_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  ))
_sym_db.RegisterMessage(Number)

AddedResult = _reflection.GeneratedProtocolMessageType('AddedResult', (_message.Message,), dict(
  DESCRIPTOR = _ADDEDRESULT,
  __module__ = 'adder_pb2'
  # @@protoc_insertion_point(class_scope:AddedResult)
  ))
_sym_db.RegisterMessage(AddedResult)



_ADDER = _descriptor.ServiceDescriptor(
  name='Adder',
  full_name='Adder',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=87,
  serialized_end=126,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='Adder.Add',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_ADDEDRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDER)

DESCRIPTOR.services_by_name['Adder'] = _ADDER

# @@protoc_insertion_point(module_scope)
